---
- name: Deploy Qpid Proton Python client cli-proton-python
  docker_container:
    name: cli-proton-python
    image: rhmessagingqe/cli-proton-python
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-proton-python
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3

- name: Deploy RHEA NodeJS client cli-rhea
  docker_container:
    name: cli-rhea
    image: rhmessagingqe/cli-rhea
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-rhea
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3

- name: Deploy clients cli-java
  docker_container:
    name: cli-java
    image: rhmessagingqe/cli-java
    state: started
    recreate: yes
    command: "sh"
    interactive: yes
    networks:
      - name: lab0
        aliases:
          - cli-java
        links:
          - Broker.M.I2
          - Broker.S.I2
          - Broker.M.E3
          - Broker.S.E3
          - Router.I1
          - Router.I2
          - Router.I3
          - Router.E1
          - Router.E2
          - Router.E3
