---
  - name: Create directory for large messages
    file:
      path: "{{ playbook_dir }}/clients-data/msgs"
      state: directory

  - name: Generate 1KiB large message
    include_tasks: tasks/create_file.yml
    vars:
      size: "{{ 2**10 }}"
      name: "msg_1kib.txt"
      path: "{{ playbook_dir }}/clients-data/msgs"
  
  - name: Generate 10KiB large message
    include_tasks: tasks/create_file.yml
    vars:
      size: "{{ 2**10*10 }}"
      name: "msg_10kib.txt"
      path: "{{ playbook_dir }}/clients-data/msgs"

  - name: Generate 1MiB large message
    include_tasks: tasks/create_file.yml
    vars:
      size: "{{ 2**20 }}"
      name: "msg_1mib.txt"
      path: "{{ playbook_dir }}/clients-data/msgs"

  - name: Generate 10MiB large message
    include_tasks: tasks/create_file.yml
    vars:
      size: "{{ 2**20*10 }}"
      name: "msg_10mib.txt"
      path: "{{ playbook_dir }}/clients-data/msgs"

  - name: Generate 100MiB large message
    include_tasks: tasks/create_file.yml
    vars:
      size: "{{ 2**20*100 }}"
      name: "msg_100mib.txt"
      path: "{{ playbook_dir }}/clients-data/msgs"

  - name: Generate checksum
    shell: "shasum msg_* > msgs.sha1sum"
    args:
      chdir: "{{ playbook_dir }}/clients-data/msgs/"