---
- hosts: routers
  tasks:
    # Create config directory
    - name: "Creating router configuration directory"
      file:
        path: /var/lib/qdrouterd
        state: directory
        mode: 0755

- hosts: Router.I1
  tasks:
    # Copy Interior Configuration files
    - name: "Router.I1 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.I1/*"

- hosts: Router.I2
  tasks:
    # Copy Interior Configuration files
    - name: "Router.I2 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.I2/*"

- hosts: Router.I3
  tasks:
    # Copy Interior Configuration files
    - name: "Router.I3 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.I3/*"

- hosts: Router.E1
  tasks:
    # Copy Edge Configuration files
    - name: "Router.E1 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.E1/*"

- hosts: Router.E2
  tasks:
    # Copy Edge Configuration files
    - name: "Router.E2 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.E2/*"

- hosts: Router.E3
  tasks:
    # Copy Edge Configuration files
    - name: "Router.E3 - Copying router configuration files"
      copy:
        src: "{{ item }}"
        dest: /var/lib/qdrouterd
      with_fileglob:
        - "{{ inventory_dir }}/files/configs/Router.E3/*"
