- hosts: routers
  roles:
    - role: ansible-service-creator
      service_opts:
        qdrouterdcustom:
          Enabled: Yes
          Started: Yes
          ExecStart: "/usr/sbin/qdrouterd -c /var/lib/qdrouterd/qdrouterd.conf"
          User: "qdrouterd"
          Group: "qdrouterd"
          State: "restarted"
