---
- name: "Creating configuration directories"
  file:
    path: "{{ inventory_dir }}/files/configs//{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - Router.I1
    - Router.I2
    - Router.I3
    - Router.E1
    - Router.E2
    - Router.E3
    - broker-interior/master
    - broker-interior/slave
    - broker-edge/master
    - broker-edge/slave

- name: "Copying Router.I1 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.I1"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.I1/*"

- name: "Copying Router.I2 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.I2"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.I2/*"

- name: "Copying Router.I3 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.I3"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.I3/*"

- name: "Copying Router.E1 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.E1"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.E1/*"

- name: "Copying Router.E2 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.E2"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.E2/*"

- name: "Copying Router.E3 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/Router.E3"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/Router.E3/*"

- name: "Copying Broker.M.I2 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/broker-interior/master"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/broker-interior/master/*"

- name: "Copying Broker.S.I2 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/broker-interior/slave"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/broker-interior/slave/*"

- name: "Copying Broker.M.E3 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/broker-edge/master"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/broker-edge/master/*"

- name: "Copying Broker.S.E3 configuration files"
  copy:
    src: "{{ item }}"
    dest: "{{ inventory_dir }}/files/configs/broker-edge/slave"
  with_fileglob:
    - "{{ inventory_dir }}/files/configs/broker-edge/slave/*"

- name: "Enabling write access to containers"
  command: "chcon -Rt svirt_sandbox_file_t {{ inventory_dir }}/files/configs"
