- hosts: localhost

  pre_tasks:
    - name: "Required variables provided"
      assert:
        that:
          - "{{ item }} != ''"
        msg: "{{ item }} is a required variable"
      with_items:
        - external_ip
    - include: ../../common/run_client_containers.yml
    - include: ../../common/iqa_testsuite_environment.yml

  roles:
    - role: ansible-interconnect-image
      openshift_template_name: "amq-interconnect-1-basic-to-router"
      openshift_template_url: "https://raw.githubusercontent.com/rh-messaging-qe/iqa_topologies/dlenoch-openshift2/qpid-dispatch/openshift/templates/interconnect-1-basic-to-router.yml"
      openshift_template_variables:
        - "IMAGE_STREAM_NAMESPACE={{ openshift_project }}"
        - "ROUTER1_IP={{ ROUTER1_IP }}"

