- hosts: localhost

  roles:
    - role: ansible-interconnect-image
      openshift_template_name: "amq-interconnect-1-tls-auth-to-router"
      openshift_template_url: ""
      openshift_template_variables:
        - "IMAGE_STREAM_NAMESPACE={{ openshift_project }}"
        - "ROUTER1_IP={{ ROUTER1_IP }}"
      inter_router_certs: true
      client_ca: true
